version: '3'
services:
  troubleshooter:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    networks: 
      - samnet
networks:
  samnet:
    external: true    