// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ADGroup is the predicate function for adgroup builders.
type ADGroup func(*sql.Selector)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// ApplicationCategory is the predicate function for applicationcategory builders.
type ApplicationCategory func(*sql.Selector)

// Community is the predicate function for community builders.
type Community func(*sql.Selector)

// CommunityCategory is the predicate function for communitycategory builders.
type CommunityCategory func(*sql.Selector)

// Partner is the predicate function for partner builders.
type Partner func(*sql.Selector)

// PartnerPageLinkFragment is the predicate function for partnerpagelinkfragment builders.
type PartnerPageLinkFragment func(*sql.Selector)
