// Code generated by ent, DO NOT EDIT.

package partnerpagelinkfragment

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the partnerpagelinkfragment type in the database.
	Label = "partner_page_link_fragment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLinkText holds the string denoting the link_text field in the database.
	FieldLinkText = "link_text"
	// FieldWhamPartnerURLSuffix holds the string denoting the wham_partner_url_suffix field in the database.
	FieldWhamPartnerURLSuffix = "wham_partner_url_suffix"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// Table holds the table name of the partnerpagelinkfragment in the database.
	Table = "partner_page_link_fragments"
)

// Columns holds all SQL columns for partnerpagelinkfragment fields.
var Columns = []string{
	FieldID,
	FieldLinkText,
	FieldWhamPartnerURLSuffix,
	FieldDisplayOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PartnerPageLinkFragment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLinkText orders the results by the link_text field.
func ByLinkText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkText, opts...).ToFunc()
}

// ByWhamPartnerURLSuffix orders the results by the wham_partner_url_suffix field.
func ByWhamPartnerURLSuffix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWhamPartnerURLSuffix, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}
