// Code generated by ent, DO NOT EDIT.

package partnerpagelinkfragment

import (
	"dbapp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLTE(FieldID, id))
}

// LinkText applies equality check predicate on the "link_text" field. It's identical to LinkTextEQ.
func LinkText(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldLinkText, v))
}

// WhamPartnerURLSuffix applies equality check predicate on the "wham_partner_url_suffix" field. It's identical to WhamPartnerURLSuffixEQ.
func WhamPartnerURLSuffix(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldWhamPartnerURLSuffix, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldDisplayOrder, v))
}

// LinkTextEQ applies the EQ predicate on the "link_text" field.
func LinkTextEQ(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldLinkText, v))
}

// LinkTextNEQ applies the NEQ predicate on the "link_text" field.
func LinkTextNEQ(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNEQ(FieldLinkText, v))
}

// LinkTextIn applies the In predicate on the "link_text" field.
func LinkTextIn(vs ...string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldIn(FieldLinkText, vs...))
}

// LinkTextNotIn applies the NotIn predicate on the "link_text" field.
func LinkTextNotIn(vs ...string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNotIn(FieldLinkText, vs...))
}

// LinkTextGT applies the GT predicate on the "link_text" field.
func LinkTextGT(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGT(FieldLinkText, v))
}

// LinkTextGTE applies the GTE predicate on the "link_text" field.
func LinkTextGTE(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGTE(FieldLinkText, v))
}

// LinkTextLT applies the LT predicate on the "link_text" field.
func LinkTextLT(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLT(FieldLinkText, v))
}

// LinkTextLTE applies the LTE predicate on the "link_text" field.
func LinkTextLTE(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLTE(FieldLinkText, v))
}

// LinkTextContains applies the Contains predicate on the "link_text" field.
func LinkTextContains(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldContains(FieldLinkText, v))
}

// LinkTextHasPrefix applies the HasPrefix predicate on the "link_text" field.
func LinkTextHasPrefix(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldHasPrefix(FieldLinkText, v))
}

// LinkTextHasSuffix applies the HasSuffix predicate on the "link_text" field.
func LinkTextHasSuffix(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldHasSuffix(FieldLinkText, v))
}

// LinkTextEqualFold applies the EqualFold predicate on the "link_text" field.
func LinkTextEqualFold(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEqualFold(FieldLinkText, v))
}

// LinkTextContainsFold applies the ContainsFold predicate on the "link_text" field.
func LinkTextContainsFold(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldContainsFold(FieldLinkText, v))
}

// WhamPartnerURLSuffixEQ applies the EQ predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixEQ(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixNEQ applies the NEQ predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixNEQ(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNEQ(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixIn applies the In predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixIn(vs ...string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldIn(FieldWhamPartnerURLSuffix, vs...))
}

// WhamPartnerURLSuffixNotIn applies the NotIn predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixNotIn(vs ...string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNotIn(FieldWhamPartnerURLSuffix, vs...))
}

// WhamPartnerURLSuffixGT applies the GT predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixGT(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGT(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixGTE applies the GTE predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixGTE(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGTE(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixLT applies the LT predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixLT(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLT(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixLTE applies the LTE predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixLTE(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLTE(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixContains applies the Contains predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixContains(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldContains(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixHasPrefix applies the HasPrefix predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixHasPrefix(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldHasPrefix(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixHasSuffix applies the HasSuffix predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixHasSuffix(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldHasSuffix(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixIsNil applies the IsNil predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixIsNil() predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldIsNull(FieldWhamPartnerURLSuffix))
}

// WhamPartnerURLSuffixNotNil applies the NotNil predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixNotNil() predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNotNull(FieldWhamPartnerURLSuffix))
}

// WhamPartnerURLSuffixEqualFold applies the EqualFold predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixEqualFold(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEqualFold(FieldWhamPartnerURLSuffix, v))
}

// WhamPartnerURLSuffixContainsFold applies the ContainsFold predicate on the "wham_partner_url_suffix" field.
func WhamPartnerURLSuffixContainsFold(v string) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldContainsFold(FieldWhamPartnerURLSuffix, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.FieldLTE(FieldDisplayOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PartnerPageLinkFragment) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PartnerPageLinkFragment) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PartnerPageLinkFragment) predicate.PartnerPageLinkFragment {
	return predicate.PartnerPageLinkFragment(sql.NotPredicates(p))
}
