# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    networks: 
      - samnet
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
  mariadbadminer:
    networks: 
      - samnet
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  samnet:
    external: true      