// Code generated by ent, DO NOT EDIT.

package communitycategory

import (
	"dbapp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldName, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldDisplayOrder, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldContainsFold(FieldName, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.FieldLTE(FieldDisplayOrder, v))
}

// HasCommunity applies the HasEdge predicate on the "community" edge.
func HasCommunity() predicate.CommunityCategory {
	return predicate.CommunityCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CommunityTable, CommunityPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommunityWith applies the HasEdge predicate on the "community" edge with a given conditions (other predicates).
func HasCommunityWith(preds ...predicate.Community) predicate.CommunityCategory {
	return predicate.CommunityCategory(func(s *sql.Selector) {
		step := newCommunityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommunityCategory) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommunityCategory) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommunityCategory) predicate.CommunityCategory {
	return predicate.CommunityCategory(sql.NotPredicates(p))
}
