// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dbapp/ent/adgroup"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ADGroup is the model entity for the ADGroup schema.
type ADGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ADGroupQuery when eager-loading is set.
	Edges        ADGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ADGroupEdges holds the relations/edges for other nodes in the graph.
type ADGroupEdges struct {
	// Community holds the value of the community edge.
	Community []*Community `json:"community,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CommunityOrErr returns the Community value or an error if the edge
// was not loaded in eager-loading.
func (e ADGroupEdges) CommunityOrErr() ([]*Community, error) {
	if e.loadedTypes[0] {
		return e.Community, nil
	}
	return nil, &NotLoadedError{edge: "community"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ADGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adgroup.FieldName:
			values[i] = new(sql.NullString)
		case adgroup.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ADGroup fields.
func (ag *ADGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adgroup.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ag.ID = *value
			}
		case adgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ag.Name = value.String
			}
		default:
			ag.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ADGroup.
// This includes values selected through modifiers, order, etc.
func (ag *ADGroup) Value(name string) (ent.Value, error) {
	return ag.selectValues.Get(name)
}

// QueryCommunity queries the "community" edge of the ADGroup entity.
func (ag *ADGroup) QueryCommunity() *CommunityQuery {
	return NewADGroupClient(ag.config).QueryCommunity(ag)
}

// Update returns a builder for updating this ADGroup.
// Note that you need to call ADGroup.Unwrap() before calling this method if this ADGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (ag *ADGroup) Update() *ADGroupUpdateOne {
	return NewADGroupClient(ag.config).UpdateOne(ag)
}

// Unwrap unwraps the ADGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ag *ADGroup) Unwrap() *ADGroup {
	_tx, ok := ag.config.driver.(*txDriver)
	if !ok {
		panic("ent: ADGroup is not a transactional entity")
	}
	ag.config.driver = _tx.drv
	return ag
}

// String implements the fmt.Stringer.
func (ag *ADGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ADGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ag.ID))
	builder.WriteString("name=")
	builder.WriteString(ag.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ADGroups is a parsable slice of ADGroup.
type ADGroups []*ADGroup
