// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"dbapp/ent/application"
	"dbapp/ent/applicationcategory"
	"dbapp/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ApplicationCategoryQuery is the builder for querying ApplicationCategory entities.
type ApplicationCategoryQuery struct {
	config
	ctx             *QueryContext
	order           []applicationcategory.OrderOption
	inters          []Interceptor
	predicates      []predicate.ApplicationCategory
	withApplication *ApplicationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApplicationCategoryQuery builder.
func (acq *ApplicationCategoryQuery) Where(ps ...predicate.ApplicationCategory) *ApplicationCategoryQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *ApplicationCategoryQuery) Limit(limit int) *ApplicationCategoryQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *ApplicationCategoryQuery) Offset(offset int) *ApplicationCategoryQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *ApplicationCategoryQuery) Unique(unique bool) *ApplicationCategoryQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *ApplicationCategoryQuery) Order(o ...applicationcategory.OrderOption) *ApplicationCategoryQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// QueryApplication chains the current query on the "application" edge.
func (acq *ApplicationCategoryQuery) QueryApplication() *ApplicationQuery {
	query := (&ApplicationClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(applicationcategory.Table, applicationcategory.FieldID, selector),
			sqlgraph.To(application.Table, application.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, applicationcategory.ApplicationTable, applicationcategory.ApplicationColumn),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ApplicationCategory entity from the query.
// Returns a *NotFoundError when no ApplicationCategory was found.
func (acq *ApplicationCategoryQuery) First(ctx context.Context) (*ApplicationCategory, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{applicationcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) FirstX(ctx context.Context) *ApplicationCategory {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApplicationCategory ID from the query.
// Returns a *NotFoundError when no ApplicationCategory ID was found.
func (acq *ApplicationCategoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{applicationcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApplicationCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApplicationCategory entity is found.
// Returns a *NotFoundError when no ApplicationCategory entities are found.
func (acq *ApplicationCategoryQuery) Only(ctx context.Context) (*ApplicationCategory, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{applicationcategory.Label}
	default:
		return nil, &NotSingularError{applicationcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) OnlyX(ctx context.Context) *ApplicationCategory {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApplicationCategory ID in the query.
// Returns a *NotSingularError when more than one ApplicationCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *ApplicationCategoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{applicationcategory.Label}
	default:
		err = &NotSingularError{applicationcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApplicationCategories.
func (acq *ApplicationCategoryQuery) All(ctx context.Context) ([]*ApplicationCategory, error) {
	ctx = setContextOp(ctx, acq.ctx, "All")
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApplicationCategory, *ApplicationCategoryQuery]()
	return withInterceptors[[]*ApplicationCategory](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) AllX(ctx context.Context) []*ApplicationCategory {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApplicationCategory IDs.
func (acq *ApplicationCategoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, "IDs")
	if err = acq.Select(applicationcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *ApplicationCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, "Count")
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*ApplicationCategoryQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *ApplicationCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, "Exist")
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *ApplicationCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApplicationCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *ApplicationCategoryQuery) Clone() *ApplicationCategoryQuery {
	if acq == nil {
		return nil
	}
	return &ApplicationCategoryQuery{
		config:          acq.config,
		ctx:             acq.ctx.Clone(),
		order:           append([]applicationcategory.OrderOption{}, acq.order...),
		inters:          append([]Interceptor{}, acq.inters...),
		predicates:      append([]predicate.ApplicationCategory{}, acq.predicates...),
		withApplication: acq.withApplication.Clone(),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// WithApplication tells the query-builder to eager-load the nodes that are connected to
// the "application" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *ApplicationCategoryQuery) WithApplication(opts ...func(*ApplicationQuery)) *ApplicationCategoryQuery {
	query := (&ApplicationClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withApplication = query
	return acq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApplicationCategory.Query().
//		GroupBy(applicationcategory.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (acq *ApplicationCategoryQuery) GroupBy(field string, fields ...string) *ApplicationCategoryGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApplicationCategoryGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = applicationcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ApplicationCategory.Query().
//		Select(applicationcategory.FieldName).
//		Scan(ctx, &v)
func (acq *ApplicationCategoryQuery) Select(fields ...string) *ApplicationCategorySelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &ApplicationCategorySelect{ApplicationCategoryQuery: acq}
	sbuild.label = applicationcategory.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApplicationCategorySelect configured with the given aggregations.
func (acq *ApplicationCategoryQuery) Aggregate(fns ...AggregateFunc) *ApplicationCategorySelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *ApplicationCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !applicationcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *ApplicationCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApplicationCategory, error) {
	var (
		nodes       = []*ApplicationCategory{}
		_spec       = acq.querySpec()
		loadedTypes = [1]bool{
			acq.withApplication != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApplicationCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApplicationCategory{config: acq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := acq.withApplication; query != nil {
		if err := acq.loadApplication(ctx, query, nodes,
			func(n *ApplicationCategory) { n.Edges.Application = []*Application{} },
			func(n *ApplicationCategory, e *Application) { n.Edges.Application = append(n.Edges.Application, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (acq *ApplicationCategoryQuery) loadApplication(ctx context.Context, query *ApplicationQuery, nodes []*ApplicationCategory, init func(*ApplicationCategory), assign func(*ApplicationCategory, *Application)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ApplicationCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Application(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(applicationcategory.ApplicationColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.category_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "category_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (acq *ApplicationCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *ApplicationCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(applicationcategory.Table, applicationcategory.Columns, sqlgraph.NewFieldSpec(applicationcategory.FieldID, field.TypeUUID))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationcategory.FieldID)
		for i := range fields {
			if fields[i] != applicationcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *ApplicationCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(applicationcategory.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = applicationcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApplicationCategoryGroupBy is the group-by builder for ApplicationCategory entities.
type ApplicationCategoryGroupBy struct {
	selector
	build *ApplicationCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *ApplicationCategoryGroupBy) Aggregate(fns ...AggregateFunc) *ApplicationCategoryGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *ApplicationCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, "GroupBy")
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationCategoryQuery, *ApplicationCategoryGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *ApplicationCategoryGroupBy) sqlScan(ctx context.Context, root *ApplicationCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApplicationCategorySelect is the builder for selecting fields of ApplicationCategory entities.
type ApplicationCategorySelect struct {
	*ApplicationCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *ApplicationCategorySelect) Aggregate(fns ...AggregateFunc) *ApplicationCategorySelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *ApplicationCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, "Select")
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationCategoryQuery, *ApplicationCategorySelect](ctx, acs.ApplicationCategoryQuery, acs, acs.inters, v)
}

func (acs *ApplicationCategorySelect) sqlScan(ctx context.Context, root *ApplicationCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
