// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dbapp/ent/application"
	"dbapp/ent/applicationcategory"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ApplicationCategoryCreate is the builder for creating a ApplicationCategory entity.
type ApplicationCategoryCreate struct {
	config
	mutation *ApplicationCategoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (acc *ApplicationCategoryCreate) SetName(s string) *ApplicationCategoryCreate {
	acc.mutation.SetName(s)
	return acc
}

// SetDisplayOrder sets the "display_order" field.
func (acc *ApplicationCategoryCreate) SetDisplayOrder(i int) *ApplicationCategoryCreate {
	acc.mutation.SetDisplayOrder(i)
	return acc
}

// SetID sets the "id" field.
func (acc *ApplicationCategoryCreate) SetID(u uuid.UUID) *ApplicationCategoryCreate {
	acc.mutation.SetID(u)
	return acc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (acc *ApplicationCategoryCreate) SetNillableID(u *uuid.UUID) *ApplicationCategoryCreate {
	if u != nil {
		acc.SetID(*u)
	}
	return acc
}

// AddApplicationIDs adds the "application" edge to the Application entity by IDs.
func (acc *ApplicationCategoryCreate) AddApplicationIDs(ids ...uuid.UUID) *ApplicationCategoryCreate {
	acc.mutation.AddApplicationIDs(ids...)
	return acc
}

// AddApplication adds the "application" edges to the Application entity.
func (acc *ApplicationCategoryCreate) AddApplication(a ...*Application) *ApplicationCategoryCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return acc.AddApplicationIDs(ids...)
}

// Mutation returns the ApplicationCategoryMutation object of the builder.
func (acc *ApplicationCategoryCreate) Mutation() *ApplicationCategoryMutation {
	return acc.mutation
}

// Save creates the ApplicationCategory in the database.
func (acc *ApplicationCategoryCreate) Save(ctx context.Context) (*ApplicationCategory, error) {
	acc.defaults()
	return withHooks(ctx, acc.sqlSave, acc.mutation, acc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (acc *ApplicationCategoryCreate) SaveX(ctx context.Context) *ApplicationCategory {
	v, err := acc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acc *ApplicationCategoryCreate) Exec(ctx context.Context) error {
	_, err := acc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acc *ApplicationCategoryCreate) ExecX(ctx context.Context) {
	if err := acc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acc *ApplicationCategoryCreate) defaults() {
	if _, ok := acc.mutation.ID(); !ok {
		v := applicationcategory.DefaultID()
		acc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acc *ApplicationCategoryCreate) check() error {
	if _, ok := acc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ApplicationCategory.name"`)}
	}
	if _, ok := acc.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "ApplicationCategory.display_order"`)}
	}
	return nil
}

func (acc *ApplicationCategoryCreate) sqlSave(ctx context.Context) (*ApplicationCategory, error) {
	if err := acc.check(); err != nil {
		return nil, err
	}
	_node, _spec := acc.createSpec()
	if err := sqlgraph.CreateNode(ctx, acc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	acc.mutation.id = &_node.ID
	acc.mutation.done = true
	return _node, nil
}

func (acc *ApplicationCategoryCreate) createSpec() (*ApplicationCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &ApplicationCategory{config: acc.config}
		_spec = sqlgraph.NewCreateSpec(applicationcategory.Table, sqlgraph.NewFieldSpec(applicationcategory.FieldID, field.TypeUUID))
	)
	if id, ok := acc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := acc.mutation.Name(); ok {
		_spec.SetField(applicationcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := acc.mutation.DisplayOrder(); ok {
		_spec.SetField(applicationcategory.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if nodes := acc.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   applicationcategory.ApplicationTable,
			Columns: []string{applicationcategory.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApplicationCategoryCreateBulk is the builder for creating many ApplicationCategory entities in bulk.
type ApplicationCategoryCreateBulk struct {
	config
	err      error
	builders []*ApplicationCategoryCreate
}

// Save creates the ApplicationCategory entities in the database.
func (accb *ApplicationCategoryCreateBulk) Save(ctx context.Context) ([]*ApplicationCategory, error) {
	if accb.err != nil {
		return nil, accb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(accb.builders))
	nodes := make([]*ApplicationCategory, len(accb.builders))
	mutators := make([]Mutator, len(accb.builders))
	for i := range accb.builders {
		func(i int, root context.Context) {
			builder := accb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, accb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, accb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, accb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (accb *ApplicationCategoryCreateBulk) SaveX(ctx context.Context) []*ApplicationCategory {
	v, err := accb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (accb *ApplicationCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := accb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (accb *ApplicationCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := accb.Exec(ctx); err != nil {
		panic(err)
	}
}
