// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"dbapp/ent/community"
	"dbapp/ent/communitycategory"
	"dbapp/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CommunityCategoryQuery is the builder for querying CommunityCategory entities.
type CommunityCategoryQuery struct {
	config
	ctx           *QueryContext
	order         []communitycategory.OrderOption
	inters        []Interceptor
	predicates    []predicate.CommunityCategory
	withCommunity *CommunityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommunityCategoryQuery builder.
func (ccq *CommunityCategoryQuery) Where(ps ...predicate.CommunityCategory) *CommunityCategoryQuery {
	ccq.predicates = append(ccq.predicates, ps...)
	return ccq
}

// Limit the number of records to be returned by this query.
func (ccq *CommunityCategoryQuery) Limit(limit int) *CommunityCategoryQuery {
	ccq.ctx.Limit = &limit
	return ccq
}

// Offset to start from.
func (ccq *CommunityCategoryQuery) Offset(offset int) *CommunityCategoryQuery {
	ccq.ctx.Offset = &offset
	return ccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ccq *CommunityCategoryQuery) Unique(unique bool) *CommunityCategoryQuery {
	ccq.ctx.Unique = &unique
	return ccq
}

// Order specifies how the records should be ordered.
func (ccq *CommunityCategoryQuery) Order(o ...communitycategory.OrderOption) *CommunityCategoryQuery {
	ccq.order = append(ccq.order, o...)
	return ccq
}

// QueryCommunity chains the current query on the "community" edge.
func (ccq *CommunityCategoryQuery) QueryCommunity() *CommunityQuery {
	query := (&CommunityClient{config: ccq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ccq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(communitycategory.Table, communitycategory.FieldID, selector),
			sqlgraph.To(community.Table, community.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, communitycategory.CommunityTable, communitycategory.CommunityPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(ccq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommunityCategory entity from the query.
// Returns a *NotFoundError when no CommunityCategory was found.
func (ccq *CommunityCategoryQuery) First(ctx context.Context) (*CommunityCategory, error) {
	nodes, err := ccq.Limit(1).All(setContextOp(ctx, ccq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{communitycategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) FirstX(ctx context.Context) *CommunityCategory {
	node, err := ccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommunityCategory ID from the query.
// Returns a *NotFoundError when no CommunityCategory ID was found.
func (ccq *CommunityCategoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ccq.Limit(1).IDs(setContextOp(ctx, ccq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{communitycategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommunityCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommunityCategory entity is found.
// Returns a *NotFoundError when no CommunityCategory entities are found.
func (ccq *CommunityCategoryQuery) Only(ctx context.Context) (*CommunityCategory, error) {
	nodes, err := ccq.Limit(2).All(setContextOp(ctx, ccq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{communitycategory.Label}
	default:
		return nil, &NotSingularError{communitycategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) OnlyX(ctx context.Context) *CommunityCategory {
	node, err := ccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommunityCategory ID in the query.
// Returns a *NotSingularError when more than one CommunityCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (ccq *CommunityCategoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ccq.Limit(2).IDs(setContextOp(ctx, ccq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{communitycategory.Label}
	default:
		err = &NotSingularError{communitycategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommunityCategories.
func (ccq *CommunityCategoryQuery) All(ctx context.Context) ([]*CommunityCategory, error) {
	ctx = setContextOp(ctx, ccq.ctx, "All")
	if err := ccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommunityCategory, *CommunityCategoryQuery]()
	return withInterceptors[[]*CommunityCategory](ctx, ccq, qr, ccq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) AllX(ctx context.Context) []*CommunityCategory {
	nodes, err := ccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommunityCategory IDs.
func (ccq *CommunityCategoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ccq.ctx.Unique == nil && ccq.path != nil {
		ccq.Unique(true)
	}
	ctx = setContextOp(ctx, ccq.ctx, "IDs")
	if err = ccq.Select(communitycategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ccq *CommunityCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ccq.ctx, "Count")
	if err := ccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ccq, querierCount[*CommunityCategoryQuery](), ccq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) CountX(ctx context.Context) int {
	count, err := ccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ccq *CommunityCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ccq.ctx, "Exist")
	switch _, err := ccq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ccq *CommunityCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := ccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommunityCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ccq *CommunityCategoryQuery) Clone() *CommunityCategoryQuery {
	if ccq == nil {
		return nil
	}
	return &CommunityCategoryQuery{
		config:        ccq.config,
		ctx:           ccq.ctx.Clone(),
		order:         append([]communitycategory.OrderOption{}, ccq.order...),
		inters:        append([]Interceptor{}, ccq.inters...),
		predicates:    append([]predicate.CommunityCategory{}, ccq.predicates...),
		withCommunity: ccq.withCommunity.Clone(),
		// clone intermediate query.
		sql:  ccq.sql.Clone(),
		path: ccq.path,
	}
}

// WithCommunity tells the query-builder to eager-load the nodes that are connected to
// the "community" edge. The optional arguments are used to configure the query builder of the edge.
func (ccq *CommunityCategoryQuery) WithCommunity(opts ...func(*CommunityQuery)) *CommunityCategoryQuery {
	query := (&CommunityClient{config: ccq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ccq.withCommunity = query
	return ccq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommunityCategory.Query().
//		GroupBy(communitycategory.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ccq *CommunityCategoryQuery) GroupBy(field string, fields ...string) *CommunityCategoryGroupBy {
	ccq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommunityCategoryGroupBy{build: ccq}
	grbuild.flds = &ccq.ctx.Fields
	grbuild.label = communitycategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.CommunityCategory.Query().
//		Select(communitycategory.FieldName).
//		Scan(ctx, &v)
func (ccq *CommunityCategoryQuery) Select(fields ...string) *CommunityCategorySelect {
	ccq.ctx.Fields = append(ccq.ctx.Fields, fields...)
	sbuild := &CommunityCategorySelect{CommunityCategoryQuery: ccq}
	sbuild.label = communitycategory.Label
	sbuild.flds, sbuild.scan = &ccq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommunityCategorySelect configured with the given aggregations.
func (ccq *CommunityCategoryQuery) Aggregate(fns ...AggregateFunc) *CommunityCategorySelect {
	return ccq.Select().Aggregate(fns...)
}

func (ccq *CommunityCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ccq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ccq); err != nil {
				return err
			}
		}
	}
	for _, f := range ccq.ctx.Fields {
		if !communitycategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ccq.path != nil {
		prev, err := ccq.path(ctx)
		if err != nil {
			return err
		}
		ccq.sql = prev
	}
	return nil
}

func (ccq *CommunityCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommunityCategory, error) {
	var (
		nodes       = []*CommunityCategory{}
		_spec       = ccq.querySpec()
		loadedTypes = [1]bool{
			ccq.withCommunity != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommunityCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommunityCategory{config: ccq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ccq.withCommunity; query != nil {
		if err := ccq.loadCommunity(ctx, query, nodes,
			func(n *CommunityCategory) { n.Edges.Community = []*Community{} },
			func(n *CommunityCategory, e *Community) { n.Edges.Community = append(n.Edges.Community, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ccq *CommunityCategoryQuery) loadCommunity(ctx context.Context, query *CommunityQuery, nodes []*CommunityCategory, init func(*CommunityCategory), assign func(*CommunityCategory, *Community)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*CommunityCategory)
	nids := make(map[uuid.UUID]map[*CommunityCategory]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(communitycategory.CommunityTable)
		s.Join(joinT).On(s.C(community.FieldID), joinT.C(communitycategory.CommunityPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(communitycategory.CommunityPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(communitycategory.CommunityPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*CommunityCategory]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Community](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "community" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (ccq *CommunityCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ccq.querySpec()
	_spec.Node.Columns = ccq.ctx.Fields
	if len(ccq.ctx.Fields) > 0 {
		_spec.Unique = ccq.ctx.Unique != nil && *ccq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ccq.driver, _spec)
}

func (ccq *CommunityCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(communitycategory.Table, communitycategory.Columns, sqlgraph.NewFieldSpec(communitycategory.FieldID, field.TypeUUID))
	_spec.From = ccq.sql
	if unique := ccq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ccq.path != nil {
		_spec.Unique = true
	}
	if fields := ccq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, communitycategory.FieldID)
		for i := range fields {
			if fields[i] != communitycategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ccq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ccq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ccq *CommunityCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ccq.driver.Dialect())
	t1 := builder.Table(communitycategory.Table)
	columns := ccq.ctx.Fields
	if len(columns) == 0 {
		columns = communitycategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ccq.sql != nil {
		selector = ccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ccq.ctx.Unique != nil && *ccq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ccq.predicates {
		p(selector)
	}
	for _, p := range ccq.order {
		p(selector)
	}
	if offset := ccq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ccq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommunityCategoryGroupBy is the group-by builder for CommunityCategory entities.
type CommunityCategoryGroupBy struct {
	selector
	build *CommunityCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ccgb *CommunityCategoryGroupBy) Aggregate(fns ...AggregateFunc) *CommunityCategoryGroupBy {
	ccgb.fns = append(ccgb.fns, fns...)
	return ccgb
}

// Scan applies the selector query and scans the result into the given value.
func (ccgb *CommunityCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ccgb.build.ctx, "GroupBy")
	if err := ccgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommunityCategoryQuery, *CommunityCategoryGroupBy](ctx, ccgb.build, ccgb, ccgb.build.inters, v)
}

func (ccgb *CommunityCategoryGroupBy) sqlScan(ctx context.Context, root *CommunityCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ccgb.fns))
	for _, fn := range ccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ccgb.flds)+len(ccgb.fns))
		for _, f := range *ccgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ccgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommunityCategorySelect is the builder for selecting fields of CommunityCategory entities.
type CommunityCategorySelect struct {
	*CommunityCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ccs *CommunityCategorySelect) Aggregate(fns ...AggregateFunc) *CommunityCategorySelect {
	ccs.fns = append(ccs.fns, fns...)
	return ccs
}

// Scan applies the selector query and scans the result into the given value.
func (ccs *CommunityCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ccs.ctx, "Select")
	if err := ccs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommunityCategoryQuery, *CommunityCategorySelect](ctx, ccs.CommunityCategoryQuery, ccs, ccs.inters, v)
}

func (ccs *CommunityCategorySelect) sqlScan(ctx context.Context, root *CommunityCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ccs.fns))
	for _, fn := range ccs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ccs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
