// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dbapp/ent/partnerpagelinkfragment"
	"dbapp/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PartnerPageLinkFragmentQuery is the builder for querying PartnerPageLinkFragment entities.
type PartnerPageLinkFragmentQuery struct {
	config
	ctx        *QueryContext
	order      []partnerpagelinkfragment.OrderOption
	inters     []Interceptor
	predicates []predicate.PartnerPageLinkFragment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PartnerPageLinkFragmentQuery builder.
func (pplfq *PartnerPageLinkFragmentQuery) Where(ps ...predicate.PartnerPageLinkFragment) *PartnerPageLinkFragmentQuery {
	pplfq.predicates = append(pplfq.predicates, ps...)
	return pplfq
}

// Limit the number of records to be returned by this query.
func (pplfq *PartnerPageLinkFragmentQuery) Limit(limit int) *PartnerPageLinkFragmentQuery {
	pplfq.ctx.Limit = &limit
	return pplfq
}

// Offset to start from.
func (pplfq *PartnerPageLinkFragmentQuery) Offset(offset int) *PartnerPageLinkFragmentQuery {
	pplfq.ctx.Offset = &offset
	return pplfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pplfq *PartnerPageLinkFragmentQuery) Unique(unique bool) *PartnerPageLinkFragmentQuery {
	pplfq.ctx.Unique = &unique
	return pplfq
}

// Order specifies how the records should be ordered.
func (pplfq *PartnerPageLinkFragmentQuery) Order(o ...partnerpagelinkfragment.OrderOption) *PartnerPageLinkFragmentQuery {
	pplfq.order = append(pplfq.order, o...)
	return pplfq
}

// First returns the first PartnerPageLinkFragment entity from the query.
// Returns a *NotFoundError when no PartnerPageLinkFragment was found.
func (pplfq *PartnerPageLinkFragmentQuery) First(ctx context.Context) (*PartnerPageLinkFragment, error) {
	nodes, err := pplfq.Limit(1).All(setContextOp(ctx, pplfq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{partnerpagelinkfragment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) FirstX(ctx context.Context) *PartnerPageLinkFragment {
	node, err := pplfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PartnerPageLinkFragment ID from the query.
// Returns a *NotFoundError when no PartnerPageLinkFragment ID was found.
func (pplfq *PartnerPageLinkFragmentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pplfq.Limit(1).IDs(setContextOp(ctx, pplfq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{partnerpagelinkfragment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pplfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PartnerPageLinkFragment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PartnerPageLinkFragment entity is found.
// Returns a *NotFoundError when no PartnerPageLinkFragment entities are found.
func (pplfq *PartnerPageLinkFragmentQuery) Only(ctx context.Context) (*PartnerPageLinkFragment, error) {
	nodes, err := pplfq.Limit(2).All(setContextOp(ctx, pplfq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{partnerpagelinkfragment.Label}
	default:
		return nil, &NotSingularError{partnerpagelinkfragment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) OnlyX(ctx context.Context) *PartnerPageLinkFragment {
	node, err := pplfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PartnerPageLinkFragment ID in the query.
// Returns a *NotSingularError when more than one PartnerPageLinkFragment ID is found.
// Returns a *NotFoundError when no entities are found.
func (pplfq *PartnerPageLinkFragmentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pplfq.Limit(2).IDs(setContextOp(ctx, pplfq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{partnerpagelinkfragment.Label}
	default:
		err = &NotSingularError{partnerpagelinkfragment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pplfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PartnerPageLinkFragments.
func (pplfq *PartnerPageLinkFragmentQuery) All(ctx context.Context) ([]*PartnerPageLinkFragment, error) {
	ctx = setContextOp(ctx, pplfq.ctx, "All")
	if err := pplfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PartnerPageLinkFragment, *PartnerPageLinkFragmentQuery]()
	return withInterceptors[[]*PartnerPageLinkFragment](ctx, pplfq, qr, pplfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) AllX(ctx context.Context) []*PartnerPageLinkFragment {
	nodes, err := pplfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PartnerPageLinkFragment IDs.
func (pplfq *PartnerPageLinkFragmentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pplfq.ctx.Unique == nil && pplfq.path != nil {
		pplfq.Unique(true)
	}
	ctx = setContextOp(ctx, pplfq.ctx, "IDs")
	if err = pplfq.Select(partnerpagelinkfragment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pplfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pplfq *PartnerPageLinkFragmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pplfq.ctx, "Count")
	if err := pplfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pplfq, querierCount[*PartnerPageLinkFragmentQuery](), pplfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) CountX(ctx context.Context) int {
	count, err := pplfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pplfq *PartnerPageLinkFragmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pplfq.ctx, "Exist")
	switch _, err := pplfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pplfq *PartnerPageLinkFragmentQuery) ExistX(ctx context.Context) bool {
	exist, err := pplfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PartnerPageLinkFragmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pplfq *PartnerPageLinkFragmentQuery) Clone() *PartnerPageLinkFragmentQuery {
	if pplfq == nil {
		return nil
	}
	return &PartnerPageLinkFragmentQuery{
		config:     pplfq.config,
		ctx:        pplfq.ctx.Clone(),
		order:      append([]partnerpagelinkfragment.OrderOption{}, pplfq.order...),
		inters:     append([]Interceptor{}, pplfq.inters...),
		predicates: append([]predicate.PartnerPageLinkFragment{}, pplfq.predicates...),
		// clone intermediate query.
		sql:  pplfq.sql.Clone(),
		path: pplfq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LinkText string `json:"link_text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PartnerPageLinkFragment.Query().
//		GroupBy(partnerpagelinkfragment.FieldLinkText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pplfq *PartnerPageLinkFragmentQuery) GroupBy(field string, fields ...string) *PartnerPageLinkFragmentGroupBy {
	pplfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PartnerPageLinkFragmentGroupBy{build: pplfq}
	grbuild.flds = &pplfq.ctx.Fields
	grbuild.label = partnerpagelinkfragment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LinkText string `json:"link_text,omitempty"`
//	}
//
//	client.PartnerPageLinkFragment.Query().
//		Select(partnerpagelinkfragment.FieldLinkText).
//		Scan(ctx, &v)
func (pplfq *PartnerPageLinkFragmentQuery) Select(fields ...string) *PartnerPageLinkFragmentSelect {
	pplfq.ctx.Fields = append(pplfq.ctx.Fields, fields...)
	sbuild := &PartnerPageLinkFragmentSelect{PartnerPageLinkFragmentQuery: pplfq}
	sbuild.label = partnerpagelinkfragment.Label
	sbuild.flds, sbuild.scan = &pplfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PartnerPageLinkFragmentSelect configured with the given aggregations.
func (pplfq *PartnerPageLinkFragmentQuery) Aggregate(fns ...AggregateFunc) *PartnerPageLinkFragmentSelect {
	return pplfq.Select().Aggregate(fns...)
}

func (pplfq *PartnerPageLinkFragmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pplfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pplfq); err != nil {
				return err
			}
		}
	}
	for _, f := range pplfq.ctx.Fields {
		if !partnerpagelinkfragment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pplfq.path != nil {
		prev, err := pplfq.path(ctx)
		if err != nil {
			return err
		}
		pplfq.sql = prev
	}
	return nil
}

func (pplfq *PartnerPageLinkFragmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PartnerPageLinkFragment, error) {
	var (
		nodes = []*PartnerPageLinkFragment{}
		_spec = pplfq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PartnerPageLinkFragment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PartnerPageLinkFragment{config: pplfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pplfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pplfq *PartnerPageLinkFragmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pplfq.querySpec()
	_spec.Node.Columns = pplfq.ctx.Fields
	if len(pplfq.ctx.Fields) > 0 {
		_spec.Unique = pplfq.ctx.Unique != nil && *pplfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pplfq.driver, _spec)
}

func (pplfq *PartnerPageLinkFragmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(partnerpagelinkfragment.Table, partnerpagelinkfragment.Columns, sqlgraph.NewFieldSpec(partnerpagelinkfragment.FieldID, field.TypeUUID))
	_spec.From = pplfq.sql
	if unique := pplfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pplfq.path != nil {
		_spec.Unique = true
	}
	if fields := pplfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerpagelinkfragment.FieldID)
		for i := range fields {
			if fields[i] != partnerpagelinkfragment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pplfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pplfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pplfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pplfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pplfq *PartnerPageLinkFragmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pplfq.driver.Dialect())
	t1 := builder.Table(partnerpagelinkfragment.Table)
	columns := pplfq.ctx.Fields
	if len(columns) == 0 {
		columns = partnerpagelinkfragment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pplfq.sql != nil {
		selector = pplfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pplfq.ctx.Unique != nil && *pplfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pplfq.predicates {
		p(selector)
	}
	for _, p := range pplfq.order {
		p(selector)
	}
	if offset := pplfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pplfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PartnerPageLinkFragmentGroupBy is the group-by builder for PartnerPageLinkFragment entities.
type PartnerPageLinkFragmentGroupBy struct {
	selector
	build *PartnerPageLinkFragmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pplfgb *PartnerPageLinkFragmentGroupBy) Aggregate(fns ...AggregateFunc) *PartnerPageLinkFragmentGroupBy {
	pplfgb.fns = append(pplfgb.fns, fns...)
	return pplfgb
}

// Scan applies the selector query and scans the result into the given value.
func (pplfgb *PartnerPageLinkFragmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pplfgb.build.ctx, "GroupBy")
	if err := pplfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerPageLinkFragmentQuery, *PartnerPageLinkFragmentGroupBy](ctx, pplfgb.build, pplfgb, pplfgb.build.inters, v)
}

func (pplfgb *PartnerPageLinkFragmentGroupBy) sqlScan(ctx context.Context, root *PartnerPageLinkFragmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pplfgb.fns))
	for _, fn := range pplfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pplfgb.flds)+len(pplfgb.fns))
		for _, f := range *pplfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pplfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pplfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PartnerPageLinkFragmentSelect is the builder for selecting fields of PartnerPageLinkFragment entities.
type PartnerPageLinkFragmentSelect struct {
	*PartnerPageLinkFragmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pplfs *PartnerPageLinkFragmentSelect) Aggregate(fns ...AggregateFunc) *PartnerPageLinkFragmentSelect {
	pplfs.fns = append(pplfs.fns, fns...)
	return pplfs
}

// Scan applies the selector query and scans the result into the given value.
func (pplfs *PartnerPageLinkFragmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pplfs.ctx, "Select")
	if err := pplfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerPageLinkFragmentQuery, *PartnerPageLinkFragmentSelect](ctx, pplfs.PartnerPageLinkFragmentQuery, pplfs, pplfs.inters, v)
}

func (pplfs *PartnerPageLinkFragmentSelect) sqlScan(ctx context.Context, root *PartnerPageLinkFragmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pplfs.fns))
	for _, fn := range pplfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pplfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pplfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
